# Generated by Django 6.1.1 on 2026-09-28 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_outboxmessage'),
        ('tasks', '0004_task_search_index'),
    ]

    operations = [
    ]
